# Site settings
title: HOME
SEOTitle: 张嘉东的博客 | Zhang JD Blog
header-img: img/back_title.jpeg    #post-bg-desk.jpg
email: zhangjiadong@buaa.edu.com
description: "PhD Condidate,  BEIHANG UNIVERSITY"
keyword: " Zhang Jiadong, 张嘉东, SLAM, Robot"
url: "http://tiny-ke.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Hey，我是张嘉东，目前是一名北航在读博士研究生,博士课题为面向室内物体空间地图的主动SLAM研究,欢迎一起探讨~。"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     xiao-ke-story
github_username:    tiny-ke
# facebook_username:  baiying.qiu.7
bilibili_username:   59946978
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 47a9a11a9b1f5790d9e2                        #生成的clientID
  clientSecret: 0e72adb07dcf77436b9b64f261ae14e587d6106d    #生成的clientSecret
  repo: tiny-ke.github.io    #仓库名称
  owner: tiny-ke    #github用户名
  admin: tiny-ke
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
